server:
  port: 8081
spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.217.175:3306/makemoney?useUnicode=true&characterEncoding=utf-8&serveTimeZone=UTC@allowPublicKeyRetrieval=true
    username: root
    password: Yly123.0123
  cache:
    type: redis
    redis:
      time-to-live: 60000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值
  redis:
    host: 47.113.217.175
    password: Yly123.0123
mybatis:
  mapper-locations: classpath:mapper/*.xml
